{% set name = "ifes-apt-tc-data-modeling" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ifes_apt_tc_data_modeling-{{ version }}.tar.gz
  sha256: 196b7c18c40c1b2cd71ea895bc84e21b3ed450cfe346c9ad4e6cc3880f11a25a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8,<3.11
    - setuptools
    - pip
  run:
    - python >=3.8,<3.11
    - h5py >=3.6.0
    - numpy >=1.21.2
    - pandas >=1.3.2
    - ase >=3.19.0
    - radioactivedecay >=0.4.16
    - jupyterlab-h5web >=6.5.0
    - jupyterlab >=3.5.2

test:
  imports:
    - ifes_apt_tc_data_modeling
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Foster exchange about data models and work towards clear specifications of file formats and data models in the research field of atom probe microscopy.
  license: Apache-2.0
  license_file: LICENSE.txt
  home: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling
  doc_url: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling
  dev_url: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling

extra:
  recipe-maintainers:
    - srmnitc
    - mkuehbach
