{% set name = "ifes-apt-tc-data-modeling" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ifes_apt_tc_data_modeling-{{ version }}.tar.gz
  sha256: 88afa2ee40e39948211dfa1ed512867e652889d6d0a001e0caa268523563fe89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - h5py >=3.6.0
    - numpy >=1.21.2
    - ase >=3.19.0
    - radioactivedecay>=0.4.16
    - pandas
    - tables
    - flatdict
    - xmltodict
    - jupyter
    - jupyterlab
    - jupyterlab_h5web

test:
  imports:
    - ifes_apt_tc_data_modeling
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Exchange about data models and specifications of file formats in atom probe research.
  license: Apache-2.0
  license_file: LICENSE.txt
  home: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling
  doc_url: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling
  dev_url: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling

extra:
  recipe-maintainers:
    - srmnitc
    - mkuehbach
